### ISSUE TITLE
Is it possible to add some key works that specifies the spectrometer name in the configuration file?

### ISSUE THREAD

**Issue by r-yamada1998** [necst-telescope/neclib#278]
**Motivation**

I do not want to specify the ROS topic name that is saved in the necstdb when loading the data. To realise this, the keyword in the config file of neclib should somewhat be connected to the necstdb list_tables. Could you consider this issue?

**Comment by KaoruNishikawa** [comment]
@r-yamada1998 
Thank you for the feature request!

First of all, I think the information is not something dependent on NECST *system* configuration, but should be bound to data itself.

Also, there will be no significant difference between the use of ROS topic name and config parameter, because both keywords have single definition ([config.toml](https://github.com/necst-telescope/neclib/blob/a37a69ea4273d534d12d97d6b52c478025250271/neclib/src/config.toml) / [definitions.py](https://github.com/necst-telescope/necst/blob/d100df7d10d9e3a40652e2e1e24af125ca999c02/necst/definitions.py)), so the chance of change or fluctuation is equally low.

**I'd like to suggest that the use of topic namespace will be suitable.** The design of implementation follows:

1. Store the data 'kind' as table metadata (using `necstdb.table.header`)
   - **Pros**
     - (WRITE) Simple implementation, just add header entry in `neclib.recorders`.
     - (READ) Simple read-out, enabling uniform list of the information like `necstdb.get_info`
       ```python
       # PoC
       {db.open_table(table).header.get("data-kind", None) for table in db.list_tables()}
       ```
   - **Cons**
     - (WRITE) Auto-detection of the kind may use topic namespace. Conversion from the namespace to kind is a little bit redundant.
     - (WRITE) May require complicated algorithm to uniformly classify the topics, since namespace definitions are in ROS package, hence not accessible from neclib.
     - (BOTH) Database formats other than necstdb may not support the custom metadata (e.g., sqlite doesn't support such metadata).
2. Judge the data kind by data namespace
   - **Pros**
     - (BOTH) No additional implementation required on database handlers.
       - So no pros or cons are discussed on WRITE-ing the information.
     - (READ) User can choose the resolution of the classification.
       ```python
       prefix = f"necst-{config.observatory}-"
       all_observation_results = [
           tablename for tablename in db.list_tables()
           if tablename.startswith(prefix + "data")
       ]
       spectral_data = [
           tablename for tablename in db.list_tables()
           if tablename.startswith(prefix + "data-spectral")
       ]
       ```
   - **Cons**
     - (READ) You won't be provided with algorithm to judge the data kind by this package.
     - (READ) Though the namespace definitions are designed to be semantically uniform, but the uniformness may depend on usage. 
     - (READ) You can access the namespace definition list, but since it's in necst, ROS environment is required.
